#!/usr/bin/env python3
"""End-to-end smoke test over a directory of real PDFs.

Usage: python tests/test_pipeline.py /path/to/pdfs [--keep]

Hand-authored lessons only ever exercise the papers you happened to write. This
builds a synthetic lesson from whatever extract.py found in each PDF, then runs
the rest of the pipeline over it. It does not check that a lecture teaches
anything; it checks the software does not fall over on real-world layouts.

Narration is skipped: it is slow and the cue path is covered by its own test.
"""
import json
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
BIN = os.path.join(HERE, "..", "bin")
PY = sys.executable


def run(*args):
    r = subprocess.run([PY] + list(args), capture_output=True, text=True)
    return r.returncode, (r.stdout + r.stderr).strip()


def synth_lesson(outdir, name):
    """A minimal but structurally complete lesson from the extracted figures."""
    figs = json.load(open(os.path.join(outdir, "figures.json")))
    slides = [{
        "kicker": "Test",
        "title": f"Synthetic lesson for {name}",
        "big": "Generated by the pipeline smoke test.",
        "points": ["First point.", "Second point."],
        "narration": "One sentence about this. A second sentence about it.",
        "focus": [None, "point:1"],
        "check": {"q": "Is this a real question?", "a": "No.", "why": "It is a smoke test."},
    }]
    for f in figs[:4]:
        slides.append({
            "title": f"{f['label']} from page {f['page']}",
            "figure": f["file"],
            "figureLabel": f["label"],
            "figureNote": f["caption"][:200] or "no caption",
            "points": ["A point about the figure."],
            "narration": "Here is a figure. Look at it closely.",
            "focus": [None, "figure"],
        })
    lesson = {
        "paper": {"title": name, "short": name[:28], "venue": "test", "file": name},
        "facts": [{"q": f"Fact about {name}?", "a": "Yes."}],
        "slides": slides,
    }
    path = os.path.join(outdir, "lesson.json")
    json.dump(lesson, open(path, "w"), indent=1)
    return path, len(figs)


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: test_pipeline.py <dir-of-pdfs> [--keep]")
    src = sys.argv[1]
    keep = "--keep" in sys.argv
    pdfs = sorted(f for f in os.listdir(src) if f.lower().endswith(".pdf"))
    if not pdfs:
        sys.exit(f"no PDFs in {src}")

    tmp = tempfile.mkdtemp(prefix="paper-lecture-smoke-")
    failures, total_figs = [], 0

    for pdf in pdfs:
        name = os.path.splitext(pdf)[0]
        out = os.path.join(tmp, name)
        stage = "extract"
        code, msg = run(os.path.join(BIN, "extract.py"), os.path.join(src, pdf), out)
        if code == 0:
            lesson, nfig = synth_lesson(out, name)
            total_figs += nfig
            for stage, script, extra in (
                ("check", "check.py", []),
                ("render", "render.py", []),
                ("deck", "deck.py", ["-o", os.path.join(out, "d.apkg")]),
            ):
                code, msg = run(os.path.join(BIN, script), lesson, *extra)
                if code != 0:
                    break
        if code != 0:
            failures.append((name, stage, msg.splitlines()[-1][:110] if msg else "?"))
            print(f"FAIL  {name[:52]:<52} at {stage}")
        else:
            html = os.path.join(out, "lecture.html")
            size = os.path.getsize(html) // 1024
            print(f"ok    {name[:52]:<52} {nfig:>2} figs  {size:>5} KB")

    print(f"\n{len(pdfs) - len(failures)}/{len(pdfs)} papers through the full pipeline, "
          f"{total_figs} figures extracted")
    for name, stage, msg in failures:
        print(f"  {name}\n    {stage}: {msg}")
    if keep:
        print(f"\noutput kept in {tmp}")
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
